server:
  port: 8080

spring:
  main:
    allow-circular-references: true
  # 配置数据库的连接信息
  datasource:
    url: jdbc:mysql://localhost:3306/sky_take_out?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: "2214"
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # redis配置
  data:
    redis:
      host: localhost
      port: 6379
      database: 0

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sky.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      sky:
        mapper: debug
        service: info
        controller: info

sky:
  jwt:
    # 管理端员工生成jwt令牌相关配置
      # 设置jwt签名加密时使用的秘钥
    admin-secret-key: eden
      # 设置jwt过期时间
    admin-ttl: 7200000
      # 设置前端传递过来的令牌名称
    admin-token-name: token
    # 用户端微信用户生成jwt令牌相关配置
    user-secret-key: admin
    user-ttl: 7200000
    user-token-name: authentication

  # 阿里云OSS配置
  alioss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    bucketName: management-sky-take-out
    region: cn-beijing

  # 配置微信小程序
  wechat:
    appid: wx7ec0b16178bb6e85
    secret: 2193b78ece7bdd8b6259169c817cbf9a

  # 配置店铺地址和百度地图的AK
  shop:
    address: "北京市海淀区上地十街10号北京科技园"
  baidu:
    ak: "0yb7FOOnKzIsEoDe8J7HIZaYZsmv4dXN"

# 配置Swagger
springdoc:
  swagger-ui:
    path: /swagger-ui.html  # Swagger UI 访问路径
    enabled: true           # 启用 Swagger UI
  api-docs:
    path: /v3/api-docs      # OpenAPI JSON 访问路径
    enabled: true           # 启用 OpenAPI JSON